sudo: true
language: python
python:
  - "2.7"
env:
  - TOX_ENV=docs
  - TOX_ENV=pep8
  - TOX_ENV=py27
  - TOX_ENV=validate-local-blueprint
  - TOX_ENV=validate-multicloud-blueprint
  - TOX_ENV=execute-local-blueprint

install:
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod +x ~/.ssh/authorized_keys
  - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf
  - git clone --depth=50 --branch=master https://github.com/aria-tosca/aria-examples.git aria-examples
  - pip install tox

script:
  - tox -e $TOX_ENV

deploy:

  - provider: pypi
    server: https://pypi.python.org/pypi
    on:
      tags: true
      all_branches: true
      condition: $TOX_ENV = py27
    user: cosmo-maint
    password:
      secure: "lrlg/zQ6upGA58dqY1f0KcqORmJNPwHILOYY4cmlIz3Zy/GQ4jlvC30+vhSFgF3D5s021w4pJL377M1R9InsuL0FDnIdZV92d/fff94s7irs+vLOmj025KaYzlbzJhOom3MOYEYiQLJKxHDJS1HaS2DrIw/oB6Bl2yxCQGlb8hYiiXjNDOaZ7NAHxZ0SNgzKxPp93Q6aYWNJQp+IPIXQb27HnOMsTj5wNdSiHdUTckDa2CFAmCoG3R3sf63zlx0c/UWjFdU6+cfdG2tBHobkZuPfX+VxQZ45YqLhWDNCFo+wfymFkplC12WVIRuH3AS23/3ddNxmqtY/Ccm3MmE7mZGZKxUw+lsk0HjEJYgVNNgOyW+tcbnM5WTuoTUWLv6b0JWjxhUnHJxq2sKoeZTLDTrp6PjCuREvh/2VWRLEj7o6dpFrCyTiQdWVKAu7jtycjIultRp68zGar6Ei96E7eAPLHz73AYv9loO68+HDzU6ZB8Fq6f27qXcNHRb3/Fjfn4EF+pi1zuoUvD0DZAmSl/0RKNwiqVp/5ck3MvnrT1oE0PZgW6k7/vCedZebgM89NbZyWrVSL35ssw276cXywc92C49rsS0pCoi7BdFL+Do2q+POXf1Y5q48MQDPsuRgxAOE1Frhx/oXyMn7qaVjpTc917L+vbEGTCm1uCXdFzQ="

  - provider: pypi
    server: https://testpypi.python.org/pypi
    on:
      tags: true
      all_branches: true
      condition: $TOX_ENV = py27
    user: cosmo-maint
    password:
      secure: "pbAA+13BgWIeD5D+elnynLUbZ02qFvF0AKAbZFX7jNCRkpLqcl8fMPFCwA150KTh1C0MabUQlau5Z708tjYO9zWLRo+w/6KupQ2rj6u+sAdnyYu+p3BXXlQ4+GDFWxmV/vsqNdJaKJC4DGnACDNwfXaKyus9wJ4YGZ7AYMuDegRtIF0P5nsRC7YFOdBUBuov5RIuaPGpFK8p3JHajTaYn2fBC7Ydhi40589j/ljocIVX+eWGSQA+Tqi21G7Q/B8i0d4DxBaeb/IlzJ/Rdhikhc68WRfVfqAL9QrBCJiMcH0Xutev3JSyXdl0R44PYa5HiYiHodgsAKzupHjdSwkqg/pUJb9a+IHiikrKuXc2vCiNsUsI1RW5RhjoGnO0c6grJW9u9Vj3KOANQ4irOcHiYiNCbEGI2aSj5xG+g9OQOqJcpfczURP3Fo/1O7sxS8bOICY6XQrjmxu86N8gAiyRTIqPBFonzEAcWszSQtE3kn/Fo/T1vM44X2gSKFOP9MVEc9rxihUp2VbCkjTzgE8mvCkdJXap6YwvYTqRilZs5GDdedeV+HDt7jIYtxv+Cao0tGJxZ/bewnBaQ3ad91LMbdB8jwD5IVUA6NvgX4huv9imE36SgWIV/ufgsGMMCN9sHZTViuqucbnswjRsrsdFBRC2IW1B1fm7Iwr3JCue50s="

after_deploy:
  - git clone https://github.com/cloudify-cosmo/travis-utils.git
  - python travis-utils/validate_pypi.py -v -b $TRAVIS_BRANCH || exit 1

notifications:
  flowdock: a73d66c41c6e4406e1c47e042dfd2b59
