sudo: false
language: python
python:
  - "2.7"
env:
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=py27

install:
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod +x ~/.ssh/authorized_keys
  - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf
  - git clone --depth=50 --branch=master https://github.com/cloudify-cosmo/cloudify-nodecellar-example.git cloudify-nodecellar-example

  - pip install tox

script:
  - tox -e $TOX_ENV
  - pip install -e .
  - aria init -p cloudify-nodecellar-example/local-blueprint.yaml
  - aria execute -w install
  - aria execute -w uninstall
