colors: false

logging:

  # path to a file where cli logs will be saved.
  filename: {{ log_path }}

  # configuring level per logger
  loggers:

    # main logger of the cli. provides basic descriptions for executed operations.
    aria_cli.cli.main: info
