logging:

  # path to a file where cli logs will be saved.
  filename: /var/folders/qb/5cydtf5923s1mytbvg3vkb3c0000gn/T/cloudify-anna/cloudify-cli.log

  # configuring level per logger
  loggers:

    # main logger of the cli. provides basic descriptions for executed operations.
    cloudify.cli.main: info

    # rest client http logs, including headers.
    cloudify.rest_client.http: info
